### ISSUE TITLE
Teensy 4.1 Support

### ISSUE THREAD

**Issue by dennism1997** [PaulStoffregen/Tlc5940#17]
Hi,
i have a project that needs tlc5940 support on the Teensy 41.
Are there any development plans for supporting the 4.1?

**Comment by astekachev** [comment]
Hi,
I also have a project that needs tlc5940 support on Teensy 4.1.

**Comment by George-PR** [comment]
Thanks for updating this to support Teensy 4.1.
Would a release be possible?
It would be great if IDEs (Teensyduino, PlatformIO..) could load this latest version.

**Comment by PaulStoffregen** [comment]
Tagged release 0.16
https://github.com/PaulStoffregen/Tlc5940/releases/tag/0.16
