### ISSUE TITLE
tlc_servos.h for Teensy3.1?

### ISSUE THREAD

**Issue by mattby** [PaulStoffregen/Tlc5940#3]
Hi Paul-

From your web page at http://www.pjrc.com/teensy/td_libs_Tlc5940.html, "special servo motor mode (tlc_servo.h) only works on Teensy++ 2.0, and Teensy++ 1.0".  

Any chance you could add support for support Teensy 3.1?  I'm sure you're super busy, but I'm pretty sure you'd be far more efficient at getting this to work than I would.  Maybe other folks are using Teensy 3.1 for tons of servos?  

Great boards, by the way,

Thanks for any consideration,
Mattby

**Comment by PaulStoffregen** [comment]
I have a very long TO-DO list, and sadly this isn't even on the list.

For connecting lots of servo motors to Teensy 3.1, look at the PulsePosition library.

http://www.pjrc.com/teensy/td_libs_PulsePosition.html
