### ISSUE TITLE
Using Timer3 on ATmega32U4

### ISSUE THREAD

**Issue by foojman** [PaulStoffregen/Tlc5940#4]
Sorry if this is not the place for this. I have been doing a lot of searches trying to resolve this but have had no luck.

Can this library be used when I am also trying to use Timer3 on an ATmega32U4. I am using a Sparkfun Pro Micro (5V 16MHz) to control 4 daisy chained TLC5940s. However, I also want to use Timer3 to control when the LEDs are turned on and off.

I had been using the delay() function in the Arduino loop to control timing but I thought that using Timer3 would be more precise. However, when I try it the two seem to conflict.

Here is the test code I am running. It should just set the brightness of the LEDs attached to the TLC chips to a constant brightness and then Timer3 should just blink the on board LED on and off at 4 Hz. Instead to TLC LEDs flash very quickly (50Hz?) and the on board LED appears dim.

```
#include "Tlc5940.h"

int RXLED = 17;
unsigned int timer3_counter;

void setup()
{
  pinMode(RXLED, OUTPUT);
  
  InitializeTimer3();

  Tlc.init(256);
}

ISR(TIMER3_OVF_vect)        // interrupt service routine 
{
  TCNT3 = timer3_counter;   // preload timer
  digitalWrite(RXLED, digitalRead(RXLED) ^ 1);
}

void loop()
{
// your program here...
}


void InitializeTimer3(void)
{
  // initialize timer3 
  noInterrupts();           // disable all interrupts
  TCCR3A = 0;               // set entire TCCR3A register to 0
  TCCR3B = 0;               // set entire TCCR3B register to 0
  
  // Set timer3_counter to the correct value for our interrupt interval
  //timer3_counter = 64911; // preload timer 65536-16MHz/256/100Hz
  //timer3_counter = 64286; // preload timer 65536-16MHz/256/50Hz
  //timer3_counter = 34286;   // preload timer 65536-16MHz/256/2Hz
  timer3_counter = 49911;   // preload timer 65536-16MHz/256/4Hz
  
  TCNT3 = timer3_counter;   // preload timer
  TCCR3B |= (1 << CS32);    // 256 prescaler 
  TIMSK3 |= (1 << TOIE3);   // enable timer overflow interrupt
  interrupts();             // enable all interrupts
}
```

FYI, I first tried using your TimerThree library, but that didn't work either.

Am I doing something wrong or are the two libraries not compatible?

Thanks,

Greg

**Comment by PaulStoffregen** [comment]
I'm sorry, I can't provide support for Sparkfun Pro Micro.  I really can't provide any support for this library either, unless it's not working on hardware I directly support (pretty much only Teensy).  Like most free open source software, it comes with no support.

The best I can do is point you to this code which initializes the timers.

https://github.com/PaulStoffregen/Tlc5940/blob/master/Tlc5940.cpp#L129

Perhaps you could read that code to answer your question, or modify it to suit your needs.  But I can't provide any support to help you do so.
